server:
  port: 4003
spring.cloud.stream:
  function:
    definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-event
    paymentEventConsumer-in-0:
      destination: payment-event
    inventoryEventConsumer-in-0:
      destination: inventory-event
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    tomcat:
      default-auto-commit: true
      initial-size: 20
      max-active: 50
      max-idle: 15
      max-wait: 20000
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          format_sql: false
      show-sql: false
